// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVNAjGOLUsLrwcPJjjfdvG6OvRWcu3YNA',
    appId: '1:385376012479:web:686269a0defc532c249e0a',
    messagingSenderId: '385376012479',
    projectId: 'xpenso-tracker',
    authDomain: 'xpenso-tracker.firebaseapp.com',
    storageBucket: 'xpenso-tracker.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDef0-pnacMzLb49DF3EMOklLp-U0FG_Rw',
    appId: '1:385376012479:android:ea32659d8bc4b58a249e0a',
    messagingSenderId: '385376012479',
    projectId: 'xpenso-tracker',
    storageBucket: 'xpenso-tracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6UaUbSKyMM0lH4xLp7jZRnn8JYXZ4yVs',
    appId: '1:385376012479:ios:26c8544195a7dced249e0a',
    messagingSenderId: '385376012479',
    projectId: 'xpenso-tracker',
    storageBucket: 'xpenso-tracker.appspot.com',
    iosBundleId: 'com.example.xpenso',
  );
}
